CREATE USER kjh IDENTIFIED BY kjh1234 DEFAULT TABLESPACE users TEMPORARY
TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO kjh;
GRANT CREATE VIEW, CREATE SYNONYM TO kjh;
ALTER USER kjh ACCOUNT UNLOCK;


  CREATE TABLE SMARTPHONE
   (   P_ID NUMBER NOT NULL, 
   P_NAME VARCHAR2(50), 
   P_PRICE NUMBER, 
   P_MANUFACTURER VARCHAR2(30), 
   P_PROCESSOR VARCHAR2(100), 
   P_MEMORY VARCHAR2(100),
   P_DISPLAY VARCHAR2(100),
   P_NETWORK VARCHAR2(100),
   P_PROXIMITY_COMMUNICATION VARCHAR2(100),
   P_SATELLITE_NAVIGATION VARCHAR2(100),
   P_CAMERA VARCHAR2(300), 
   P_BATTERY VARCHAR2(100), 
   P_OPERATOR VARCHAR2(100), 
   P_STANDARD VARCHAR2(100), 
   P_COLOR VARCHAR2(100), 
   P_TERMINAL VARCHAR2(100), 
   P_BIOSECURITY VARCHAR2(100), 
   P_ETC VARCHAR2(100), 
    PRIMARY KEY (P_ID)
);


CREATE SEQUENCE num_seq
START WITH 1
INCREMENT BY 1;


create or replace trigger NUM_SEQUENCE_TRIGGER
BEFORE INSERT
ON smartphone
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
	SELECT num_seq.nextval INTO :NEW.id FROM dual;
END;